package config

import (
    "os"
    "path/filepath"
    "strings"

    "gopkg.in/yaml.v3"
)

// DefaultPath returns the default configuration path: ~/.zazi/config.yaml
func DefaultPath() (string, error) {
    home, err := os.UserHomeDir()
    if err != nil {
        return "", err
    }
    return filepath.Join(home, ".zazi", "config.yaml"), nil
}

// Load reads the YAML configuration from disk, merging with defaults for any
// missing fields. If the file does not exist, a default config is returned.
func Load(path string) (*Config, error) {
    if path == "" {
        var err error
        path, err = DefaultPath()
        if err != nil {
            return nil, err
        }
    }

    // Start with defaults
    cfg := NewDefault()

    // If file doesn't exist, return defaults
    data, err := os.ReadFile(path)
    if err != nil {
        if os.IsNotExist(err) {
            return cfg, nil
        }
        return nil, err
    }

    // Unmarshal and merge
    var loaded Config
    if err := yaml.Unmarshal(data, &loaded); err != nil {
        return nil, err
    }
    if loaded.DataPath != "" {
        cfg.DataPath = loaded.DataPath
    }
    if loaded.LogLevel != "" {
        cfg.LogLevel = loaded.LogLevel
    }
    if loaded.ServerPort != 0 {
        cfg.ServerPort = loaded.ServerPort
    }
    if loaded.LLMProviders != nil {
        cfg.LLMProviders = loaded.LLMProviders
    }
    if loaded.Secrets != nil {
        cfg.Secrets = loaded.Secrets
    }
    return cfg, nil
}

// Save writes the given config to disk as YAML. It is safe to call multiple times
// and will overwrite the file if necessary.
func Save(path string, cfg *Config) error {
    if cfg == nil {
        cfg = NewDefault()
    }
    if path == "" {
        var err error
        path, err = DefaultPath()
        if err != nil {
            return err
        }
    }
    // Ensure parent directory exists
    if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
        return err
    }
    // Expand user-relative paths for storage clarity
    // User of the config is responsible for Path expansions when using DataPath
    b, err := yaml.Marshal(cfg)
    if err != nil {
        return err
    }
    // Optional header to help humans understand the file
    header := []byte("# zsistant config (auto-generated by zazi)\n")
    content := append(header, b...)
    return os.WriteFile(path, content, 0o644)
}

// EnsureDirs creates the required data subdirectories under the configured DataPath.
func EnsureDirs(cfg *Config) error {
    if cfg == nil {
        cfg = NewDefault()
    }
    base := ExpandPath(cfg.DataPath)
    dirs := []string{
        filepath.Join(base, "agents"),
        filepath.Join(base, "logs"),
        filepath.Join(base, "cache"),
        filepath.Join(base, "backups"),
    }
    for _, d := range dirs {
        if err := os.MkdirAll(d, 0o755); err != nil {
            return err
        }
        // Also ensure directory is writable by testing a temp file root-access
        test := filepath.Join(d, ".dir_test")
        if err := os.WriteFile(test, []byte("ok"), 0o644); err == nil {
            _ = os.Remove(test)
        }
    }
    return nil
}

// expandPath expands a path that may start with '~' to the user's home directory.
func ExpandPath(p string) string {
    if p == "" {
        return p
    }
    if strings.HasPrefix(p, "~") {
        if home, err := os.UserHomeDir(); err == nil {
            // join ensures proper path separators
            return filepath.Join(home, p[1:])
        }
    }
    return p
}
